// <auto-generated />
using System;
using ClamManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimManagement.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240128121956_setstringToNullble3")]
    partial class setstringToNullble3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClaimManagement.Data.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdjudicationResult")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("AmountApprovedOriginalCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountApprovedPlanCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountClaimedOriginalCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountClaimedPlanCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountPaidOriginalCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountPaidPlanCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ClaimNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CoPaymentOriginalCurrency")
                        .HasColumnType("longtext");

                    b.Property<string>("CoPaymentPlanCurrency")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiagnosticCode")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosticDescription")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsReimbursement")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NetworkProviderId")
                        .HasColumnType("int");

                    b.Property<string>("NetworkProviderInvoiceNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalCurrencyCode")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientName")
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PlanCurrencyCode")
                        .HasColumnType("longtext");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcedureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TPAClaimReferenceNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("TPAId")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentCountry")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NetworkProviderId");

                    b.HasIndex("TPAId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("ClaimManagement.Data.Entities.NetworkProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NameCode")
                        .HasColumnType("longtext");

                    b.Property<string>("OfficialName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneLandLine")
                        .HasColumnType("longtext");

                    b.Property<string>("RepresentativeEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("RepresentativeMobileNo")
                        .HasColumnType("longtext");

                    b.Property<string>("RepresentativeName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NetworkProviders");
                });

            modelBuilder.Entity("ClaimManagement.Data.Entities.TPA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NameCode")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneLandLine")
                        .HasColumnType("longtext");

                    b.Property<string>("RepresentativeEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("RepresentativeMobileNo")
                        .HasColumnType("longtext");

                    b.Property<string>("RepresentativeName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TPAs");
                });

            modelBuilder.Entity("NetworkProviderTPA", b =>
                {
                    b.Property<int>("NetworkProvidersId")
                        .HasColumnType("int");

                    b.Property<int>("TPAsId")
                        .HasColumnType("int");

                    b.HasKey("NetworkProvidersId", "TPAsId");

                    b.HasIndex("TPAsId");

                    b.ToTable("NetworkProviderTPA");
                });

            modelBuilder.Entity("ClaimManagement.Data.Entities.Claim", b =>
                {
                    b.HasOne("ClaimManagement.Data.Entities.NetworkProvider", "NetworkProvider")
                        .WithMany("Claims")
                        .HasForeignKey("NetworkProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimManagement.Data.Entities.TPA", "TPA")
                        .WithMany("Claims")
                        .HasForeignKey("TPAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkProvider");

                    b.Navigation("TPA");
                });

            modelBuilder.Entity("NetworkProviderTPA", b =>
                {
                    b.HasOne("ClaimManagement.Data.Entities.NetworkProvider", null)
                        .WithMany()
                        .HasForeignKey("NetworkProvidersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimManagement.Data.Entities.TPA", null)
                        .WithMany()
                        .HasForeignKey("TPAsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimManagement.Data.Entities.NetworkProvider", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("ClaimManagement.Data.Entities.TPA", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
